site_name: Mason Recipes
site_author: David Beihl
site_description: A collection of delicious family recipes
repo_url: https://github.com/masonrecipes/masonrecipes.github.io
repo_name: masonrecipes
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    - scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.footer
    - navigation.indexes

nav:
  - Home: index.md
  - Recipes:
    - Appetizers & Dips:
      - Air Fried Buffalo Wings: recipes/appetizers_and_dips/air_fried_buffalo_wings.md
      - Beer Cheese: recipes/appetizers_and_dips/beer_cheese.md
      - Buffalo Chicken Dip: recipes/appetizers_and_dips/buffalo_chicken_dip.md
      - Chorizo Queso: recipes/appetizers_and_dips/chorizo_queso.md
      - Dill Dip: recipes/appetizers_and_dips/dill_dip.md
      - Feta Bake Dip: recipes/appetizers_and_dips/feta_bake_dip.md
      - Guacamole: recipes/appetizers_and_dips/guacamole.md
      - Mexican Cream Cheese Dip: recipes/appetizers_and_dips/mexican_cream_cheese_dip.md
      - Rosemary Nuts: recipes/appetizers_and_dips/rosemary_nuts.md
      - Spring Rolls: recipes/appetizers_and_dips/spring_rolls.md
      - Tomato Basil Bruschetta: recipes/appetizers_and_dips/tomato_basil_bruschetta.md
      - Tapenade: recipes/appetizers_and_dips/tapenade.md
    - Main Courses:
      - Caribbean Paella: recipes/main_courses/caribbean_paella.md
      - Cheesy Keto Chicken Fajita Casserole: recipes/main_courses/cheesy_keto_chicken_fajita_casserole.md
      - Chicken Crust Pizza: recipes/main_courses/chicken_crust_pizza.md
      - Chicken Curry Casserole: recipes/main_courses/chicken_curry_casserole.md
      - Chicken Cutlets: recipes/main_courses/chicken_cutlets.md
      - Chicken Tikka Masala: recipes/main_courses/chicken_tikka_masala.md
      - Chipotle Fish Tacos: recipes/main_courses/chipotle_fish_tacos.md
      - Italian Chorizo Shakshouka: recipes/main_courses/italian_chorizo_shakshouka.md
      - Mikes Quick Fajitas: recipes/main_courses/mikes_quick_fajitas.md
      - My Favorite Casserole: recipes/main_courses/my_favorite_casserole.md
      - Pork Carnitas: recipes/main_courses/pork_carnitas.md
      - Pork Ribs in Slow Cooker: recipes/main_courses/pork_ribs_in_slow_cooker.md
      - Salmon with Mango Salsa: recipes/main_courses/salmon_with_mango_salsa.md
      - Sausage Mozarella Pizza: recipes/main_courses/sausage_mozarella_pizza.md
      - Scotts Pot Roast: recipes/main_courses/scotts_pot_roast.md
      - Sherrys Sunday Roast: recipes/main_courses/sherrys_sunday_roast.md
      - Simple Crockpot Chicken Fajitas: recipes/main_courses/simple_crockpot_chicken_fajitas.md
      - Slow Cooked Pork Ribs: recipes/main_courses/slow_cooked_pork_ribs.md
      - Smoked Meatloaf: recipes/main_courses/smoked_meatloaf.md
      - Smoked Pork Butt: recipes/main_courses/smoked_pork_butt.md
      - Steak Tips Au Gratin: recipes/main_courses/steak_tips_au_gratin.md
      - Stephanies Super Slow Sloppy Joes: recipes/main_courses/stephanies_super_slow_sloppy_joes.md
      - Tacos Al Carbon: recipes/main_courses/tacos_al_carbon.md
      - Tatanya with Everything: recipes/main_courses/tatanya_with_everything.md
      - Wedding Casserole: recipes/main_courses/wedding_casserole.md
      - White Bean Chicken Chili: recipes/main_courses/white_bean_chicken_chili.md
    - Sides & Soups:
      - Baked Zucchini Casserole: recipes/sides_and_soups/baked_zucchini_casserole.md
      - Crock Pot Potato Soup: recipes/sides_and_soups/crock_pot_potato_soup.md
      - Garlicky Oven Fries: recipes/sides_and_soups/garlicky_oven_fries.md
      - Greek Salad: recipes/sides_and_soups/greek_salad.md
      - Homemade Noodles: recipes/sides_and_soups/homemade_noodles.md
      - Italian Sausage Soup: recipes/sides_and_soups/italian_sausage_soup.md
      - Julies Tortilla Soup: recipes/sides_and_soups/julies_tortilla_soup.md
      - Kickin Turnip Greens: recipes/sides_and_soups/kickin_turnip_greens.md
      - Mikes Mighty Meaty Soup: recipes/sides_and_soups/mikes_mighty_meaty_soup.md
      - Potato Kale Soup: recipes/sides_and_soups/potato_kale_soup.md
      - Santa Fe Soup: recipes/sides_and_soups/santa_fe_soup.md
      - Spicy Brussel Sprouts: recipes/sides_and_soups/spicy_brussel_sprouts.md
      - Strawberry Salad: recipes/sides_and_soups/strawberry_salad.md
      - Sweet & Sour Cabbage & Barley Soup: recipes/sides_and_soups/sweet_amp_sour_cabbage_amp_barley_soup.md
      - Taco Soup Quick and Easy: recipes/sides_and_soups/taco_soup_quick_and_easy.md
      - That Good Salad: recipes/sides_and_soups/that_good_salad.md
      - Vegetable Beef and Barley Soup: recipes/sides_and_soups/vegetable_beef_and_barley_soup.md
      - Wild Rice Salad: recipes/sides_and_soups/wild_rice_salad.md
      - Wild Rice Soup: recipes/sides_and_soups/wild_rice_soup.md
    - Desserts:
      - Almond Pistachio Fat Bombs: recipes/desserts/almond_pistachio_fat_bombs.md
      - Beihl Oatmeal Cookies: recipes/desserts/beihl_oatmeal_cookies.md
      - Best White Chocolate Chip Cookies: recipes/desserts/best_white_chocolate_chip_cookies.md
      - Buckeyes: recipes/desserts/buckeyes.md
      - Butterscotch Pie: recipes/desserts/butterscotch_pie.md
      - Chocolate Chip Cookies: recipes/desserts/chocolate_chip_cookies.md
      - Coconut Chocolate Fat Bomb Squares: recipes/desserts/coconut_chocolate_fat_bomb_squares_like_mounds.md
      - Coconut Cupcakes with Cream Cheese Frosting: recipes/desserts/coconut_cupcakes_with_a_cream_cheese_buttercream_frosting.md
      - Fresh Apple Cake with Hot Caramel Sauce: recipes/desserts/fresh_apple_cake_with_hot_caramel_sauce.md
      - Jannys Ginger Cookies: recipes/desserts/jannys_ginger_cookies.md
      - Jans Pie Crust: recipes/desserts/jans_pie_crust.md
      - Katys Banana Pudding: recipes/desserts/katys_banana_pudding.md
      - Keto Chocolate Pudding: recipes/desserts/keto_chocolate_pudding.md
      - Keto Peanut Butter Pie: recipes/desserts/keto_peanut_butter_pie.md
      - Lemon Bars: recipes/desserts/lemon_bars.md
      - Mikes Caramels: recipes/desserts/mikes_caramels.md
      - Never Fail Fudge: recipes/desserts/never_fail_fudge.md
      - Peach Crumb Pie: recipes/desserts/peach_crumb_pie.md
      - Peanut Butter Cups: recipes/desserts/peanut_butter_cups.md
      - Protein Marshmallows: recipes/desserts/protein_marshmallows.md
      - Pumpkin Praline Cake: recipes/desserts/pumpkin_praline_cake.md
      - Red Raspberry Pie: recipes/desserts/red_raspberry_pie.md
      - Rhubarb Cookies: recipes/desserts/rhubarb_cookies.md
      - Rum Cake to Die For: recipes/desserts/rum_cake_to_die_for.md
      - Sherrys Cinnamon Rolls: recipes/desserts/sherrys_cinnamon_rolls.md
      - Sherrys Peanut Butter Bars: recipes/desserts/sherrys_peanut_butter_bars.md
      - Sherrys Pumpkin Cake: recipes/desserts/sherrys_pumpkin_cake.md
      - Smores Cookie Bars: recipes/desserts/smores_cookie_bars.md
      - Spicy Banana Cake or Muffins: recipes/desserts/spicy_banana_cake_or_muffins.md
      - Strawberry Cupcakes: recipes/desserts/strawberry_cupcakes.md
      - Strawberry Scones: recipes/desserts/strawberry_scones.md
      - Swedish Gingerbread: recipes/desserts/swedish_gingerbread.md
      - Texas Chocolate Sheet Cake: recipes/desserts/texas_chocolate_sheet_cake.md
      - Toasted Pecan Brown Butter Bites: recipes/desserts/toasted_pecan_brown_butter_bites.md
    - Beverages:
      - Classic Margarita: recipes/beverages/classic_margarita.md
      - Davids Sangria: recipes/beverages/davids_sangria.md
      - Keto Margarita: recipes/beverages/keto_margarita.md
      - Katys Ranch Water: recipes/beverages/katys_ranch_water.md
      - Mikes Gin Fizzy: recipes/beverages/mikes_gin_fizzy.md
      - Randy Masons Margarita: recipes/beverages/randy_masons_margarita.md
      - Rum Punch: recipes/beverages/rum_punch.md
      - Sherrys Hot Chocolate: recipes/beverages/sherrys_hot_chocolate.md
    - Sauces & Condiments:
      - Caribbean Jerk Marinade: recipes/sauces_and_condiments/caribbean_jerk_marinade.md
      - Dukes Keto Mayonnaise: recipes/sauces_and_condiments/dukes_keto_mayonnaise.md
      - Fresh Pesto: recipes/sauces_and_condiments/fresh_pesto.md
      - Green Enchilada Sauce: recipes/sauces_and_condiments/green_enchilada_sauce.md
      - Harissa Tunisian Hot Sauce: recipes/sauces_and_condiments/harissa_tunisian_hot_sauce.md
      - Spaghetti Sauce: recipes/sauces_and_condiments/spaghetti_sauce.md
      - Taco Seasoning: recipes/sauces_and_condiments/taco_seasoning.md
    - Breakfast:
      - Cindys Shrimp and Grits: recipes/breakfast/cindys_shrimp_and_grits.md
      - Mikes Amish Aunts Sausage Gravy: recipes/breakfast/mikes_amish_aunts_sausage_gravy.md
      - Sausage Brunch Casserole: recipes/breakfast/sausage_brunch_casserole.md
      - Sausage Egg and Spinach Breakfast Bowl: recipes/breakfast/sausage_egg_and_spinach_breakfast_bowl.md
    - Breads & Extras:
      - Jans Pie Crust: recipes/breads_and_extras/jans_pie_crust.md
      - Kristas Tartine Bread: recipes/breads_and_extras/kristas_tartine_bread.md
      - Oatmeal Bread: recipes/breads_and_extras/oatmeal_bread.md
      - Potato Rusks: recipes/breads_and_extras/potato_rusks.md
  - Contact: recipes/contact.md

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - md_in_html
